import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KoPa Grading System",
  description: "Generated by KopaGrade",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Added 'relative' and a fallback 'bg-black' to match your current theme */}
      <body className="min-h-full flex flex-col relative bg-black">
        
        {/* 
          Background Image Layer 
          - fixed inset-0: Stretches the div to cover the entire screen
          - z-[-1]: Sends the background behind your child components
          - opacity-30: Applies the 30% opacity strictly to the image
        */}
        <div 
          className="fixed inset-0 z-[-1] bg-[url('/background.jpg')] bg-cover bg-center bg-no-repeat opacity-30"
          aria-hidden="true"
        ></div>

        {/* Main Content (The centered card from Teacher Login 101.png) */}
        {children}
        
      </body>
    </html>
  );
}
